### ISSUE TITLE
TODO for Rust rewrite

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/chezmoi_modify_manager#8]
In rough order of importance:

* [x] Integration tests
* [X] Cross compiling:
  * [x] Linux: x86-64, ARM, Arch64. Musl?
  * [X] Windows
  * [X] OS X (limited support, cannot test locally, only via CI)
  * ~~BSDs~~: No support for executing the test using cross. No support for running tests natively on CI
* [x] CI for tests.
* [x] CI for releases.
* [x] Self updater
* [x] Migration strategy for 1.x users
* [x] User facing documentation
* [x] Document how to enable tab completion.
* [X] Create AUR packages
* [ ] Waiting for new bpaf release (see https://github.com/pacak/bpaf/discussions/197)
